### ISSUE TITLE
$this->formatQueryParams() in TwitterSearch causes incorrect search filter

### ISSUE THREAD

**Issue by Gnative** [rezozero/mixedfeed#3]
If I pass a  ['q'=>'dogs'] as queryParams to the constructor. The function formatQueryParams() turns this into q:dogs. Which is what is search for and returns tweets with content such as "Q Dogs". 
I get better return results by using below.

$this->queryParams['count'] = $count;
$body = $this->twitterConnection->get("search/tweets", $this->queryParams );

Thou I'm not sure if this is correct either.

**Comment by ambroisemaupate** [comment]
@Gnative I’m currently fixing this. You should not have to pass a `['q'=>'dogs']` parameter array as TwitterSearchFeed automatically adds the `q` param.

``` php
$body = $this->twitterConnection->get("search/tweets", [
      "q" => $this->formatQueryParams(),
      "count" => $count,
]);
```

After I’ll fix the `formatQueryParams` method, you’ll be able to use a multikey array:

``` php
   new TwitterSearchFeed(
        [
            'twitter', // do not specify a key for string searchs
            'from' => 'ambroisemaupate',
            'since' => '2015-11-01',
            'until' => date('Y-m-d'),
        ],
        'xxxx',
        'xxxx',
        'xxxx',
        'xxxx',
        $cache
    ),
```

It will generate the `q` param with `"twitter from:ambroisemaupate since:2015-11-01 until:2015-12-01"` value. It’s the right syntax according to https://dev.twitter.com/rest/public/search
